# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    pv.yaml                                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wtaylor <wtaylor@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/22 20:38:33 by wtaylor           #+#    #+#              #
#    Updated: 2021/04/10 15:00:53 by wtaylor          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
spec:
  storageClassName: manual
  volumeName: test-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi