# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    configmap.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wtaylor <wtaylor@student.21-school>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/19 14:52:31 by wtaylor           #+#    #+#              #
#    Updated: 2021/03/19 14:53:25 by wtaylor          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.100-192.168.1.250
