# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wtaylor <wtaylor@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/22 15:17:31 by wtaylor           #+#    #+#              #
#    Updated: 2021/03/28 00:05:19 by wtaylor          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: wp-db
        persistentVolumeClaim:
          claimName: wpbd-pv-claim
      containers:
      - name: mysql
        image: mysql-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/wpdb"
          name: wp-db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
   metallb.universe.tf/allow-shared-ip: sharing
spec:
  type: LoadBalancer
  selector:
    app: mysql
  loadBalancerIP: 192.168.99.100
  ports:
    # - name: http
    #   protocol: TCP
    #   port: 80
    #   targetPort: 80
    - name: ptth
      protocol: TCP
      port: 3306
      targetPort: 3306