# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    lb.yaml                                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wtaylor <wtaylor@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/09 22:22:40 by wtaylor           #+#    #+#              #
#    Updated: 2021/03/09 22:50:31 by wtaylor          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.100-192.168.99.200