# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wtaylor <wtaylor@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/20 16:28:08 by wtaylor           #+#    #+#              #
#    Updated: 2021/04/22 12:04:18 by wtaylor          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
   metallb.universe.tf/allow-shared-ip: sharing
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  loadBalancerIP: 192.168.99.100
  ports:
    - name: https
      protocol: TCP
      port: 5050
      targetPort: 5050