# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wtaylor <wtaylor@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/23 00:33:00 by wtaylor           #+#    #+#              #
#    Updated: 2021/04/24 13:20:08 by wtaylor          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 10050
        - containerPort: 10051
        - containerPort: 10052
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
   metallb.universe.tf/allow-shared-ip: sharing
spec:
  type: LoadBalancer
  selector:
    app: ftps
  loadBalancerIP: 192.168.99.100
  ports:
    - name: ftp-data
      port: 20
      protocol: TCP
    - name: ftps-port
      protocol: TCP
      port: 21
      targetPort: 21
    - name: passv-port0
      protocol: TCP
      port: 10050
      targetPort: 10050
    - name: passv-port1
      protocol: TCP
      port: 10051
      targetPort: 10051
    - name: passv-port2
      protocol: TCP
      port: 10052
      targetPort: 10052