# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wtaylor <wtaylor@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/23 00:33:00 by wtaylor           #+#    #+#              #
#    Updated: 2021/04/23 00:34:05 by wtaylor          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
   metallb.universe.tf/allow-shared-ip: sharing
spec:
  type: LoadBalancer
  selector:
    app: ftps
  loadBalancerIP: 192.168.99.100
  ports:
    - name: ftps-port
      protocol: TCP
      port: 21
      targetPort: 21